# Generated by Django 4.2.5 on 2023-10-10 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('image_data', models.BinaryField()),
            ],
        ),
    ]
